### ISSUE TITLE
Software use

### ISSUE THREAD

**Issue by tsilverman1** [CCSI-Toolset/superstructure#5]
Hello,
I am trying to learn how to utilize the software. I had it run once but haven't been able to rerun with adjusted input parameters (nor the original inputs). I'm not very familiar with Open Source or how to operate programs. I did see there is a "Status: Terminated due to a licensing error". Any suggestions? Thanks,
Tyler

**Comment by MAZamarripa** [comment]
Hello, 
Due to the size of the problem (# of variables and constraints) a GAMS license is required to use the code (or use an open source solver). 

https://www.gams.com/
Find the GAMS user's documentation 
https://www.gams.com/latest/docs/UG_MAIN.html

Once you have the GAMS license you should be able to run the code (variable bounds and initialization is important for convergence in this problem). Since, the model is an MINLP program, you can use different solvers, such as: Dicopt, BONMIN, ANTIGONE, BARON (global).
Regards,
Miguel

**Comment by ksbeattie** [comment]
Closing this issue now that @MAZamarripa has updated the readme.

@tsilverman1 please do let us know if you get a chance to test this with a GAMS license.  Thanks!
